from typing import TypedDict, Dict, Any, List, Optional
from pydantic import BaseModel

class DueDiligenceState(TypedDict):
    """
    The shared memory (State) for the LangGraph orchestrator.
    This acts as the whiteboard that all agents read from and write to.
    """
    # Inputs provided by the user
    document_path: str
    target_symbol: str
    competitors: List[str]
    
    # Outputs generated by agents (Nodes)
    parsed_document: Optional[Dict[str, Any]] # Storing as dict to easily pass through graph state
    financial_metrics: Optional[Dict[str, Any]]
    market_intelligence: Optional[Dict[str, Any]]
    
    # LLM Generated Outputs (To be built next)
    risk_assessment: str
    final_memo: str
    
    # Error tracking
    errors: List[str]
