import sys
import os
from typing import Dict, Any

# Ensure core module is importable
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from core.schemas import ParsedDocument, FinancialMetrics

class AnalysisAgent:
    """
    The Analysis Agent computes exact financial metrics deterministically.
    It enforces the 'Computation Rule' by prohibiting LLM mathematical hallucinations.
    """
    
    def analyze(self, doc: ParsedDocument) -> FinancialMetrics:
        print(f"Analysis Agent: Analyzing data from {doc.source_file}")
        metrics = FinancialMetrics()
        
        # In a real scenario, this would dynamically parse various table structures.
        # For this prototype, we'll extract data assuming a standard format 
        # (like the one generated by our sample CSV)
        
        extracted_data: Dict[str, Dict[str, float]] = {}
        
        for table in doc.tables:
            data_rows = table.get("data", [])
            for row in data_rows:
                metric_name = str(row.get("Metric", "")).strip()
                if not metric_name:
                    continue
                
                extracted_data[metric_name] = {}
                for key, value in row.items():
                    if key != "Metric":
                        try:
                            # Convert years (keys) and financial values to appropriate types
                            extracted_data[metric_name][str(key)] = float(value)
                        except ValueError:
                            continue
                            
        self._compute_ratios(extracted_data, metrics)
        self._compute_trends(extracted_data, metrics)
        self._detect_anomalies(metrics)
        
        return metrics
        
    def _compute_ratios(self, data: Dict[str, Dict[str, float]], metrics: FinancialMetrics):
        """Deterministically calculate financial ratios (e.g., Margins)."""
        revenue_data = data.get("Revenue", {})
        gross_profit_data = data.get("Gross Profit", {})
        net_income_data = data.get("Net Income", {})
        
        for year in revenue_data.keys():
            if year not in metrics.ratios:
                metrics.ratios[year] = {}
                
            rev = revenue_data.get(year, 0)
            if rev > 0:
                gp = gross_profit_data.get(year, 0)
                ni = net_income_data.get(year, 0)
                
                # Gross Profit Margin = Gross Profit / Revenue
                metrics.ratios[year]["Gross Margin (%)"] = round((gp / rev) * 100, 2)
                
                # Net Profit Margin = Net Income / Revenue
                metrics.ratios[year]["Net Margin (%)"] = round((ni / rev) * 100, 2)
                
    def _compute_trends(self, data: Dict[str, Dict[str, float]], metrics: FinancialMetrics):
        """Deterministically calculate Year-over-Year (YoY) growth."""
        for metric_name, yearly_data in data.items():
            years = sorted(yearly_data.keys())
            for i in range(1, len(years)):
                prev_year = years[i-1]
                curr_year = years[i]
                
                prev_val = yearly_data[prev_year]
                curr_val = yearly_data[curr_year]
                
                if prev_val > 0:
                    growth = ((curr_val - prev_val) / prev_val) * 100
                    trend_key = f"{prev_year}-{curr_year}"
                    
                    if metric_name not in metrics.trends:
                        metrics.trends[metric_name] = {}
                    
                    metrics.trends[metric_name][trend_key] = f"{round(growth, 2)}%"

    def _detect_anomalies(self, metrics: FinancialMetrics):
        """Flag logical inconsistencies or massive margin shrinkages."""
        rev_trends = metrics.trends.get("Revenue", {})
        ni_trends = metrics.trends.get("Net Income", {})
        
        for period in rev_trends.keys():
            if period in ni_trends:
                rev_growth = float(rev_trends[period].strip('%'))
                ni_growth = float(ni_trends[period].strip('%'))
                
                # Example anomaly rule: Revenue grows by >5%, but Net Income drops
                if rev_growth > 5.0 and ni_growth < 0:
                    metrics.anomalies.append(
                        f"Anomaly detected in {period}: Revenue grew by {rev_growth}%, "
                        f"but Net Income shrank by {ni_growth}%."
                    )
